### PR TITLE
Added an interactive example.

### PR DESCRIPTION
**Pull request by Skeen**
An interactive example can serve as grounds for implementations or as a basis for experimentation.

### CODE REVIEW

**Comment by omphalos** [comment]
@Skeen thanks for doing this!  Actually I missed github's notification, so sorry for the delay!  The example looks really good.

A few minor things:

* Can you add your example to the `build-examples` script in package.json?

* Sorry to ask for this but would you mind adjusting your code format so that it is consistent with the rest of the project?  It's using two space indents, and brackets should be formatted like this:

```function f() {
  //  do something
}```

instead of like this: 

```function f()
{
  //  do something
}```

Your code formatting style is fine I'd just like the project to be consistent with itself, if that's ok.

* I see you're copy-pasting signal-client.js and web-socket.js, but re-using the server.js file from the other example.  I wonder if maybe we should just create a `shared` folder under `examples` and put the shared files there so they can be re-used.  What do you think?

**Comment by Skeen** [comment]
Hi @omphalos

No worries about the delay.

It's currently 1am, but when I get around to it tomorrow I'll add my example to `build-examples`. Standardize the code format to fit the rest of the project and make the `shared` folder you suggest :)

Cheers.

**Comment by Skeen** [comment]
Hello @omphalos,

I have implemented the suggested changes, you can take a look at it if you please.

**Comment by omphalos** [comment]
@Skeen thanks for making these changes! Looking good.. Just one more little thing here: since webrtc-browser-e2e/server.js is shared by both examples, do you think it's a good idea to move it to shared as well?  (If you agree, I think the references to it in the example folders' .md files would need to be updated to point at the shared path as well.)

**Comment by Skeen** [comment]
Hi @omphalos,

I agree that the `server.js` file should be moved into shared. See the most recent commit.

**Comment by omphalos** [comment]
Awesome, thanks!

**Pull request merged**
