### PR TITLE
update the simple-peer package, fixes #12

### LINKED ISSUE #12: onaddstream is deprecated! Use peerConnection.ontrack instead.
The simple-peer version is outdated. This issue is triggered: https://github.com/feross/simple-peer/issues/84

It has been fixed in recent versions of simple-peer. Unfortunately, the API seems to have been changed, so that a simple update to the most recent npm version of simple-peer does not resolve the problem.

### PR DESCRIPTION
**Pull request by rriemann**

### CODE REVIEW

**Comment by omphalos** [comment]
@rriemann thank you very much for putting this together.  When I install the wrtc version in your updated README, then reinstall simple-peer, and run `npm run test`, I see the following error from mocha:

```
  33 passing (3s)
  1 failing

  1) Transports/WebRTC #send should transmit a message:
     Uncaught TypeError: onSuccess is not a function
      at node_modules/wrtc/lib/peerconnection.js:379:7
```

Do you see the same error?

**Comment by omphalos** [comment]
@rriemann doing some investigation the test error seems due to the following issue: https://github.com/feross/simple-peer/issues/122

**Comment by rriemann** [comment]
I'm impressed, the issue you mentioned got opened 7h ago and only 2h later we ran into it. That's close to real time! 😉 

I have to admit that I ran into an installation problem with wrtc 0.0.59 and I got a step further with wrtc 0.0.61. I can at least start the tests until wrtc seg faults with:

```
/usr/bin/node: symbol lookup error: /tmp/kad-webrtc/node_modules/wrtc/build/wrtc/v0.0.61/Release/node-v48-linux-x64/wrtc.node: undefined symbol: XOpenDisplay
```

**Comment by omphalos** [comment]
@rriemann yeah wrtc has had problems being installed on different platforms in the past.  I subscribed to the simple-peer issue.  When that makes some headway I can re-run the tests and potentially merge your PR.

**Comment by feross** [comment]
FYI, the simple-peer + wrtc issue is resolved

**Comment by omphalos** [comment]
@feross thanks!

**Comment by martindale** [comment]
@bookchin I just bumped into this, funnily enough.  `rtc.node: undefined symbol: XOpenDisplay` with `simple-peer@^8.1.0` and `wrtc@0.0.62`.  Digging through these other threads now...

**Pull request merged**
